### ISSUE TITLE
Make this work with Rundeck 2.6.1

### ISSUE THREAD

**Issue by diwu1989** [higanworks/rundeck-slack-incoming-webhook-plugin#10]
doesn't seem to work on rundeck 2.6

**Comment by diwu1989** [comment]
nvm looks like the latest 0.5dev might work, can u put up a jar?

**Comment by sawanoboly** [comment]
Thanks. I've added to https://github.com/higanworks/rundeck-slack-incoming-webhook-plugin/releases/tag/v0.5.dev .
