### ISSUE TITLE
Unable to Post - Rundeck 2.6.2

### ISSUE THREAD

**Issue by vinodhkumarvm** [higanworks/rundeck-slack-incoming-webhook-plugin#11]
The integrations failing with below error and I use Rundeck version 2.6.2

**Unable to POST notification after 1 tries: success for execution 32 (succeeded): server response: 500 Server Error**

**Comment by sawanoboly** [comment]
Did you tried with v0.5.0 https://github.com/higanworks/rundeck-slack-incoming-webhook-plugin/releases/tag/v0.5.dev ?

Rundeck version 2.6.2 and v0.5.dev are working on my server without problem.

**Comment by vinodhkumarvm** [comment]
Yes, I used v0.5.0 https://github.com/higanworks/rundeck-slack-incoming-webhook-plugin/releases/tag/v0.5.dev. And issue with the same.

**Comment by sawanoboly** [comment]
@vinodhkumarvm 

hmm.. 500 error is serverside.

Could you please check `rundeck/service.log` ?

**Comment by vinodhkumarvm** [comment]
Here the error from server.log

**2015-12-24 10:37:51,811 ERROR NotificationService - Notification failed [onstart,running,37]; URL https://hooks.slack.com/services/xxxxx/xxxxx/xxxxxx: Unable to POST notification after 1 tries: start for execution 37 (running): server response: 500 Server Error**

**Comment by sawanoboly** [comment]
Did you try to execute cURL example of this endpoint? And succeed?

**Comment by vinodhkumarvm** [comment]
Yes curl works perfectly.

**Comment by sawanoboly** [comment]
Do you have any idea to reproduce? I can't imagine what is problem.

**Comment by ozbillwang** [comment]
I think the ticket can be closed. 

Test with latest `higanworks/rundeck-slack-incoming-webhook-plugin`, it works fine.

**Comment by sawanoboly** [comment]
Thanks!

I'll close this once.
