### ISSUE TITLE
Is there a way to show the user that fired the job on slack?

### ISSUE THREAD

**Issue by AV4TAr** [higanworks/rundeck-slack-incoming-webhook-plugin#12]
Hi there.

We were using a plugin for hipchat that showed the user that executed the job

![image](https://cloud.githubusercontent.com/assets/281805/14176449/667a777e-f727-11e5-8b78-bc05e4323732.png)

Is there a way to add that information to slack?

**Comment by sawanoboly** [comment]
Hi,

Maybe, including `execution.user` to src/main/resources/templates/slack-incoming-message.ftl to resolve it.

**Comment by sawanoboly** [comment]
#14 resolved this issue ?
