### ISSUE TITLE
Question: Multi channel / conditional on rundeck value

### ISSUE THREAD

**Issue by guzmanbraso** [higanworks/rundeck-slack-incoming-webhook-plugin#23]
Good morning,

We have tried the plugin and works like a charm, however there are two things we were unable to do and would love to know if anyone else had the same issue and found a workaround that can share.

First problem:
We need one job to notify to two channels.

Second problem:
We need one job to notify only if rundeck variable "environment" it's "production".

Any thoughts?

**Comment by gfoligna** [comment]
Same here!
