### ISSUE TITLE
Support for custom notifications

### ISSUE THREAD

**Issue by michael-dickinson** [higanworks/rundeck-slack-incoming-webhook-plugin#26]
Is there a way to add support for custom notifications (or does this already exist?), such that notifications can be smaller and also include context variables, as well as job output if possible.

The original project that this was forked from had support for external Freemarker templates to achieve this, maybe this is already included in this plugin but unconfigurable? If not, would it be possible to add this functionality back in?

**Comment by sawanoboly** [comment]
Sorry, this plugin is not actively maintained.  If you want to use own templates instead of built in, it is better to fork and build by yourself.

**Comment by unicolet** [comment]
@michael-dickinson apologies for the long wait: we do support that now on a global or per-job basis. Better late than never :-)
